### ISSUE TITLE
I had to install ruby-macho manually

### ISSUE THREAD

**Issue by mok0** [jimeh/build-emacs-for-macos#102]
When trying to build Emacs version 29.3 I was met with a message:

`.... in 'require': cannot load such file -- macho (LoadError)`

so I had to manually install ruby-macho:

`gem install ruby-macho`

I am not a Ruby guy so I don't know if I missed a step, but it seems that macho is missing from Brewfile.

**Comment by jimeh** [comment]
Apologies, I have managed to forget to update the readme. Just running `make bootstrap` should install both Homebrew and Ruby dependencies.

I'll get the readme updated soon.
