### ISSUE TITLE
arch-dependent data dir 'Contents/MacOS/libexec/': No such file or directory

### ISSUE THREAD

**Issue by tommythorn** [jimeh/build-emacs-for-macos#108]
I hope this is the right place to report this.

I installed "GNU Emacs 31.0.50" via Mac Home Brew on an M1 MacBook Air and I'm struggling to fix
`Warning: arch-dependent data dir 'Contents/MacOS/libexec/': No such file or directory`

The README.md suggestion doesn't work on several levels:
1. there is no `/Applications/Emacs.app/Contents/MacOS/bin` (there are multiple bin-* directories though)
2. there is no `emacs` anywhere in under `/Applications/Emacs.app/Contents/MacOS`, but there is both an `Emacs` and an `emacs-nw`.
3. Launching `/Applications/Emacs.app/Contents/MacOS/Emacs` or `/Applications/Emacs.app/Contents/MacOS/emacs-nw` both results in the above warning.

(AFAICT, this is the root cause of problems I have with extensions).

**Comment by jimeh** [comment]
Sounds like you've installed the [`emacs`](https://formulae.brew.sh/cask/emacs) Cask from Homebrew, it uses binary builds of Emacs from https://emacsformacosx.com, which is unrelated to this project.

This project is for my custom build script to make it easier to build self contained Emacs applications for macOS. I do also maintain a nightly builds project that uses this script here: https://github.com/jimeh/emacs-builds (note: only stable and monthly builds offer Apple Silicon builds)

For better or worse there's a number of different ways to install Emacs on macOS, both from source and also as pre-built applications.

If it helps, here's a brief summary of the options available off the top of my head:

- Standard GNU Emacs:
  - emacsformacosx.com pre-built apps, focuses on a vanilla Emacs build with no extra bells or whistles enabled at compile time. Can be installed with `brew install --cask emacs`.
  - [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) is a Homebrew formula focused on automating the building of Emacs on your own machine with various bells and whistles enabled. It does not produce a fully self-contained Emacs.app application however.
  - [jimeh/emacs-builds](https://github.com/jimeh/emacs-builds) my own nightly and stable builds project, with a focus on fully self-contained Emacs.app applications and enabling as many useful bells and whistles at compile time as possible.
  - [jimeh/build-emacs-for-macos](https://github.com/jimeh/build-emacs-for-macos) (this project) is the underlying build script for jimeh/emacs-builds, with the same focus, but let's you easily create your own builds on your own machine.
- Forks:
  - [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport?tab=readme-ov-file) is a fork of GNU Emacs to add various macOS specific features. It is well maintained and kept up to date with GNU Emacs, but its origin is +10 years ago, and regular GNU Emacs plays much nicer with macOS now.

**Comment by tommythorn** [comment]
My apologies and thanks for the wealth of information and links.  I’ll try these options.

**Comment by tommythorn** [comment]
Installing directly from the releases of [jimeh/emacs-builds](https://github.com/jimeh/emacs-builds) works exactly as documented here (of course) and solved my problem.  Thanks again!
