### ISSUE TITLE
Add patch for alpha-background support

### ISSUE THREAD

**Issue by garyo** [jimeh/build-emacs-for-macos#111]
Here's a patch from https://github.com/jonrubens/emacs that adds support for `alpha-background` on MacOS (set alpha of background while leaving text opaque; it's great for doc popup frames). It would be great if you could add this as an option to your script -- I see you've got a few such options which download patches and apply them.

This patch applies OK to emacs master (a268496727, Aug 20 2024).
[ns-alpha-background-v2.patch](https://github.com/user-attachments/files/16682084/ns-alpha-background-v2.patch)

**Comment by jimeh** [comment]
Oh, that's neat :) 

If possible I prefer pointing the script to a URL to fetch a patch where it's likely to be updated.

Hence my question is where you got that patch file from, and is it the same as the [diff](https://github.com/emacs-mirror/emacs/compare/master...jonrubens:emacs:ns-alpha-background) between upstream `master` and jonrubes' `ns-alpha-background` branch? I can't easily check right now as I'm on my phone.

If it is the same, I should be able to use GitHub's compare patch feature and use this URL to download the patch:

```
https://github.com/emacs-mirror/emacs/compare/master...jonrubens:emacs:ns-alpha-background.patch
```

**Comment by garyo** [comment]
Great! I agree re: downloading from a URL, for sure. (It would be great if your script had an option for users to apply patches from user-specified URLs, like "--patch <url-or-file>" -- that would make it easy to try things out.) 

What I did, to be careful, is git clone jonrubes' repo, switch to his `ns-alpha-background` branch, git diff vs. his repo's master, then apply that patch to current emacs master (had to add `-l -F10` because things have diverged a bit), review that visually, then I did `git diff` to get a clean patch off master.

I did a quick test here, and yes, your github compare URL produces an identical patch to mine, when applied to current emacs-mirror master (I still have to do `patch -p1 -l`, ignoring whitespace, otherwise one hunk fails).

**Comment by jimeh** [comment]
@garyo As of v0.6.56 there's now a `-p`/`--patch` option that accepts a URL or file path to patches. And I've also added `-l` to the `patch` call, and the above github compare URL does apply to the current master commit.

I've not had a chance to actually test the patch myself though, just see if it applies at all :)

**Comment by garyo** [comment]
Thanks!

**Comment by garyo** [comment]
BTW, this is already useful: the librsvg breakage from yesterday on master can be fixed by `-p "https://git.savannah.gnu.org/cgit/emacs.git/patch/?h=emacs-30&id=f65de1019dca6398097751abefcad7e1a4637551"`

**Comment by jimeh** [comment]
Yep, I tested the alpha-background patch by also pulling in the fix commit from GitHub as a patch... lol

The alpha-background feature is pretty damn nice btw. I'll try and see if we can it a bit more officially supported as a patch either here or in emacs-plus.
