### ISSUE TITLE
Use of wrapper script in app bundle on Catalina complicates app switching

### ISSUE THREAD

**Issue by bramadams** [jimeh/build-emacs-for-macos#14]
Hi,

I just switched to Catalina, and it seems like the new wrapper script in the app bundle causes problems to switch to the emacs 28 (native compilation) app bundle using Spotlight, Alfred or by double-clicking in Finder, similar to described here for emacsformacosx: https://spin.atomicobject.com/2019/12/12/fixing-emacs-macos-catalina.

Basically, once opened, Spotlight/Alfred do not change focus to the opened app instance, while I even had Finder opening multiple app instances instead of switching the open one.

There is a workaround using Applescript, see;: https://www.alfredforum.com/topic/13807-upgrade-macos-catalina-and-alfred-4-alfred-couldnt-switch-the-window-to-emacs/, that makes pre-Catalina app switch behaviour work again, but it feels like a clutch.

Is there any way the wrapper script (which sets the right paths, for example to find GCC) could be integrated into init.el, such that it could be discarded?

PS: BTW, the app bundle I created on 10.13 worked without a hitch on 10.15, except for the above issue.

**Comment by jimeh** [comment]
That's interesting, thanks for the all the digging :)

I'll have a look at a elisp solution that can hopefully be patched into `startup.el` or something else within Emacs.app, or worst case just added by the user to their config.

**Comment by jimeh** [comment]
I've put together a bit of elisp which sets up the environment variables
relative to the executable, same way as the launcher script. Native compilation
works when it's added to the top of `early-init.el`. I think it's a bit hacky,
but it does the job.

I haven't had a chance yet to try and patch it into Emacs' own `startup.el` or
something, hopefully I'll have time to experiment with that later today or
tomorrow.

In the meantime if you want to try it out, you can either remove the launch
script manually, or create a new build with the `--no-launcher` (after clearing
out the relevant folder under `./sources/` if needed).

Then add the following snippet to the top of your `early-init.el`:

``` emacs-lisp
(let* ((path-env (getenv "PATH"))
       (library-path-env (getenv "LIBRARY_PATH"))
       (bin-dir (concat invocation-directory "bin"))
       (libexec-dir (concat invocation-directory "libexec"))
       (gcc-dir (car (file-expand-wildcards
                      (concat invocation-directory "lib-*/gcc/*"))))
       (gcc-darwin-dir (car (file-expand-wildcards
                             (concat gcc-dir "/gcc/*apple-darwin*/*"))))
       (paths (append
               (list bin-dir libexec-dir)
               (if path-env (list path-env) (list))))
       (lib-paths (append
                   (list gcc-dir gcc-darwin-dir)
                   (if library-path-env (list library-path-env) (list)))))

  (setenv "PATH" (mapconcat 'identity paths ":"))
  (setenv "LIBRARY_PATH" (mapconcat 'identity lib-paths ":")))
```

**Comment by bramadams** [comment]
I removed the launcher and put the code at the top of early-init.el, and it works great (both compilation and app-switching)!

**Comment by jimeh** [comment]
@bramadams would you mind trying the `setup-library-path-with-elisp` branch from #15?

It works for me with native-comp playing nice and all when GCC in homebrew is removed, and without any `LIBRARY_PATH` setup in `early-init.el` :)

**Comment by bramadams** [comment]
Hi, patch #15 works on my machine, just had to make a small change in the patch, see my review comment.

(Basically, I usually append the version number to my Emacs app, so adding `.*` after `Emacs` in the app's name was required to make the before advice apply.)
