### ISSUE TITLE
lisp-mode eln image not found error

### ISSUE THREAD

**Issue by Grekkor** [jimeh/build-emacs-for-macos#18]
I have built native comp emacs successfully using your script and using the latest git hash that you flagged as working but when launching it I get:

> emacs: dlopen(/Applications/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.6.0-919382e94fb290efe3ee4a93fd4035d3/lisp-mode-0189ba85598c041b7504f0a916c04219-1738806322de892570d69dfc55b437c2.eln, 1): image not found

Any help would be appreciated!

**Comment by jimeh** [comment]
Hmm, that's strange. I did just update the build script to use the new `libgccjit` Homebrew formula earlier today, and I'm afraid I didn't test it with the latest "good" commit I have listed, but a later one.

Would you mind trying it with git SHA `825e85b393a3d78ba43176ecc5bc1a9595d0fbea`? I had that successfully build earlier today and working alright so far this evening.

**Comment by babygau** [comment]
I could confirm the build script is working OK. Reinstall `gcc` and `libgccjit` and have `gccemacs` built successfully. I'm running without any problem so far.

**Comment by Grekkor** [comment]
It looks like the native-lisp folder was not situated in the MacOS folder as the build script expects it, instead it was in the root of the source folder. Essentially the build script failed when creating the symlinks because it could not find the native-lisp or eln-cache folders.

I copied the native-lisp folder into my /Applications/Emacs.app/Contents folder and now Emacs boots but it fails with:
> File is missing: Opening directory, No such file or directory, /Applications/Emacs.app/Contents/MacOS/lib/gcc

I have the feeling that I might have screwed up some env vars by following previous build instructions which did not work.

**Comment by jimeh** [comment]
@Grekkor Ah, technically the `native-lisp` folder originates in the root of the build directory, but should be copied into the relevant place within `nextstep/Emacs.app/` during Emac's own build process, and from there my build script then symlinks it. In your case it sounds like something didn't go quite right with the build in general.

As for the missing gcc folder, that makes sense if my build script didn't have a chance to finish properly, as once the regular `make` stage is done, a whole bunch of libraries need to be copied into Emacs.app and re-linked against the new embedded variants, and for native-comp specifically, it also involves copying GCC's whole `lib` folder into the app so libgccjit can work.

In this case, may I suggest you trash all relevant folders within the `sources` directory, and try again? This ensures there's no left over stuff from previous build attempts that could be causing issues.

Also, as @babygau mentioned, if you haven't done so already, ensure you've got the latest `gcc` and `libgccjit` homebrew formula installed. If you previously had the custom patched `gcc` formula, reinstall GCC with: `brew reinstall gcc`

**Comment by Grekkor** [comment]
I just did a reinstall of gcc and libgccjit and cleaned the sources folder completely. 
I ran:
> ./build-emacs-for-macos --git-sha 825e85b393a3d78ba43176ecc5bc1a9595d0fbea feature/native-comp
but I get this error during the symlinking step:
>/Library/Developer/CommandLineTools/usr/bin/make -C lib-src maybe-blessmail
make[1]: Nothing to be done for `maybe-blessmail'.
find native-lisp -type f -exec /usr/bin/install -c -m 644 -D "{}" ""/Users/grekk/Emacs/build-emacs-for-macos/sources/emacs-mirror-emacs-825e85b/nextstep/Emacs.app/Contents/MacOS/lib/emacs/28.0.50/"{}" \;
/usr/bin/install: illegal option -- D

**Comment by Grekkor** [comment]
My bad. its all working now. I forgot to run brew bundle so I had dependencies missing.

**Comment by jimeh** [comment]
Haha, yes, the dependencies are useful. Glad to hear it’s working :)

**Comment by henrymazza** [comment]
[This comment](https://github.com/jimeh/build-emacs-for-macos/issues/18#issuecomment-703785486) saved me a few times, specially the last homebrew `emacs-mac` (early 2022)  version 28.0. It looks like this bug is recurrent, it shows up in recent gnu site mailing list.

**Comment by jimeh** [comment]
@henrymazza Interesting, from what I recall the `native-lisp` folder was moved to `Contents/Frameworks/native-lisp` within the app bundle some time around last summer.

Personally I haven't had any issues since that move at least. But I've also been pretty exclusively using nightly builds from my [emacs-builds](https://github.com/jimeh/emacs-builds) project instead of building Emacs directly on my own machine. Though the nightly builds are built using the `build-emacs-for-macos` script from this project.

**Comment by henrymazza** [comment]
@jimeh i'm having the issue with homebrew's emacs-mac with last 28.0 version, and with-comp option. i think gnu's site bug is really older.
