### ISSUE TITLE
Can I build emacs 27.1 with native-comp?

### ISSUE THREAD

**Issue by Sleepful** [jimeh/build-emacs-for-macos#22]
I run doom emacs, and they only support up to emacs 27, readme says that native-comp installs eamcs 28.

What's the difference between these:

- `./build-emacs-for-macos emacs-27.1 --native-comp` 
- `./build-emacs-for-macos feature/native-comp`

**Comment by alex-numo** [comment]
`./build-emacs-for-macos emacs-27.1 --native-comp` should not build, and does not for me.
```==> INFO: Compiling with native-comp enabled
ERROR: This emacs source tree does not support native-comp```
`./build-emacs-for-macos feature/native-comp` should build 28, because the native-comp branch is based on 28

**Comment by jimeh** [comment]
In short, no. Native-comp is based on top of the current `master` branch, which is Emacs 28.

From what I recall with doom-emacs, it required Emacs 26.1 or later, with 27 being recommended. And I'm pretty sure I've toyed with doom-emacs on a native comp build without issue.

To answer your question of what the difference is between those commands:

- `./build-emacs-for-macos emacs-27.1 --native-comp` will download and build from the `emacs-27.1` branch, and due the `--native-comp` flag it will check for native-comp support in the configure script, which will fail, and it should exit with an error.
- `./build-emacs-for-macos feature/native-comp` will download and buld from the `feature/native-comp` branch. As neither `--native-comp` or `--no-native-comp` is given to explicitly enable/disable native-comp, it will attempt to detect support for native-comp, and enable it if detected.

I'm closing this issue now, but feel free to reply if you've got any more questions.
