### ISSUE TITLE
Recent "Known Good Commits" not working for me in Big Sur

### ISSUE THREAD

**Issue by powellb** [jimeh/build-emacs-for-macos#24]
I have tried numerous "Known Good Commits" to no avail on Big Sur. I did a clean install of Big Sur, installed homebrew (using the bundle), and most of the builds succeed in compilation, but launching emacs results in:

Native compiler error: (lambda (arg1 &optional) (let ((f #'yes-or-no-p)) (funcall f arg1))), Compiling /Users/powellb/.config/emacs/eln-cache/28.0.50-x86_64-apple-darwin20.1.0-49f57b89165c34ed2376cdf316ba8250/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln...
ld: library not found for -lgcc_ext.10.5
libgccjit.so: error: error invoking gcc driver

The interesting thing is that fd9e9308d27138a16e2e93417bd7ad4448fea40a works fine. After that, none of them work for me. 

I am invoking them exactly as in jimeh's list:

./build-emacs-for-macos --git-sha be907b0ba82c2a65e0468d50653cae8a7cf5f16b feature/native-comp

Everything proceeds and works as normal; however, once launched, when emacs tries to use the native-compiler it fails with the above.

Any one else experiencing this? Why would the one commit work but the others fail?

As an aside, libgccjit seems to be working fine. I have built the standard smoketest without issue, etc. It is only the commits after fd9e9308d27138a16e2e93417bd7ad4448fea40a that fail for me.

**Comment by jimeh** [comment]
I think c7daa1350bd69df172ce6484c54189d2cee8d97e fixed this. I only pushed that fix about 40 hours ago, so please update the build script if you haven't already :)

If that doesn't work, please try checking the value of the `LIBRARY_PATH` environment variable within emacs with:

`M-x describe-variable` > `process-environment`

And look for `LIBRARY_PATH=...` within it's value.

Mine for example looks like this, with `Emacs.app` placed under `/Applications/`:

```
"LIBRARY_PATH=/Applications/Emacs.app/Contents/MacOS/lib/gcc/10:/Applications/Emacs.app/Contents/MacOS/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0"
```

**Comment by powellb** [comment]
Perfect, thank you. I had updated three days ago, so I had missed that most recent push.

The be907b0 commit is now working for me. For comparison, in Emacs, my LIBRARY_PATH is:

"LIBRARY_PATH=/Applications/Emacs.app/Contents/MacOS/lib/gcc/10:/Applications/Emacs.app/Contents/MacOS/lib/gcc/10/gcc/x86_64-apple-darwin20/10.2.0"

Cheers!
