### ISSUE TITLE
dlopen image not found error for building feature/native-comp

### ISSUE THREAD

**Issue by ccqpein** [jimeh/build-emacs-for-macos#27]
I download and run `build-emacs-for-macos` on my computer this morning. Everything looks good until step [symlink_internals](https://github.com/jimeh/build-emacs-for-macos/blob/5a61a72a73672943d809c4ae3f59f106644eca33/build-emacs-for-macos#L355). 

```
==> INFO: Creating symlinks within Emacs.app needed for native-comp
Traceback (most recent call last):
	6: from ./build-emacs-for-macos:821:in `<main>'
	5: from ./build-emacs-for-macos:99:in `build'
	4: from ./build-emacs-for-macos:360:in `symlink_internals'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	1: from ./build-emacs-for-macos:365:in `block in symlink_internals'
./build-emacs-for-macos:365:in `basename': no implicit conversion of nil into String (TypeError)
```

After this, I chdir into `nextstep/Emacs.app/Contents/` and run `./MacOS/Emacs` manually. It return me 

```
emacs: dlopen(/Users/Me/Desktop/build-emacs-for-macos/sources/emacs-mirror-emacs-bd693cc/nextstep/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin20.2.0-1702cf8430b129cccc53f34c8ae4a27d/mouse-15f283fa50e83fc2aec8714353ada84c-a3299a7c327de804acf70c9bee1124bb.eln, 1): image not found
```

Is there any solutions of this error? Or I did something wrong with my env? 

My Env:
MacBook Pro
macOS 11.1

Thank you

**Comment by jimeh** [comment]
That sounds like something went wrong with building the native-comp `*.eln` files, to the point the folder they're supposed to be output to doesn't exist, but no errors were produced.

I can't say I've ever seen that behavior.

I would say try these things if you haven't already:

- Ensure you have the latest Xcode or Xcode CLI tools installed
- Ensure you have all the latest homebrew dependencies installed by running `brew bundle` from within the `build-emacs-for-macos` directory.
- Trash any folders under the `sources` directory to ensure you're starting with a clean build.
- Try running again: `./build-emacs-for-macos feature/native-comp`

**Comment by ccqpein** [comment]
I build it successfully now. I think the previous problem is I haven't run `brew bundle` before I start to build. Thank you!
