### ISSUE TITLE
Getting the ERROR: Failed to get commit info about

### ISSUE THREAD

**Issue by alexshgov** [jimeh/build-emacs-for-macos#35]
Current OS: `MacOS Big Sur 11.2.3`
`git version 2.24.3 (Apple Git-128)`

Trying to run the script on the following ruby versions:
 
- ruby-2.4.2 [ x86_64 ]
- ruby-2.5.3 [ x86_64 ]
- ruby-2.7.2 [ x86_64 ]

and getting the error
```
➜  build-emacs-for-macos git:(master) ✗ ./build-emacs-for-macos
ERROR: Failed to get commit info about:
```

Not sure what exact info about my setup I should provide to help to debug this

**Comment by jimeh** [comment]
interesting, that indeed seems to be an issue, I've been building from the `feature/native-comp` branch for so long that I didn't notice the default auto-feature has broken. I'll try and get a fix out tonight.

What it is meant to do without any arguments is build the `master` branch, for now you can work around this by passing in the master branch:

```
./build-emacs-for-macos master
```

**Comment by alexshgov** [comment]
Thanks for the rapid response @jimeh
