### ISSUE TITLE
ERROR: Failed to get commit info about: <commit SHA>

### ISSUE THREAD

**Issue by CsBigDataHub** [jimeh/build-emacs-for-macos#46]
![image](https://user-images.githubusercontent.com/23665525/119855116-446a5f00-bed7-11eb-8fd1-0fa4eb026993.png)

Ruby version - `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

on `MacOs Catalina 10.15.7`

**Comment by jimeh** [comment]
Hmmm, this looks like an issue with the GitHub API. It could be because the script makes an unauthenticated request to the API, and in some instances/contexts such requests are not allowed.

I'll try and get support added for authenticated GitHub API requests by reading the `GITHUB_TOKEN` environment variable in the next day or two.

**Comment by CsBigDataHub** [comment]
> in some instances/contexts such requests are not allowed.

Probably because I on a work VPN!. Let me try the same disabling VPN. Will update.

> I'll try and get support added for authenticated GitHub API requests by reading the `GITHUB_TOKEN` environment variable in the next day or two.

Thanks much

**Comment by CsBigDataHub** [comment]
@jimeh I can confirm that this issue only occurs when using a proxy/vpn.

The script works fine when proxy/vpn is disabled.

**Comment by jimeh** [comment]
Cool, it's definitely the GitHub API throttling un-authenticated requests based on source IP then :)... I've not had a chance to sort out `GITHUB_TOKEN` support this weekend, but should find the time in the next few days.

**Comment by jimeh** [comment]
You should now be able to avoid this issue by setting the `GITHUB_TOKEN` environment variable to a GitHub Personal Access Token, and it will make the GitHub API requests using your token, avoiding the low rate limits for unauthenticated requests.

Let me know if you have any further issues :)
