### ISSUE TITLE
Emacs won't open: LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by sandinmyjoints** [jimeh/build-emacs-for-macos#57]
I've been using the a45aed9 build for a few weeks (and before that, have used several previous builds to get native-comp for the past year or so -- thanks for your work!).
I am running macOS 10.14.6 Mojave. Today, after a reboot and installing a Safari 14.1.2 security upgrade, when I started Emacs, it failed.

```
../Emacs.2021-07-25.a45aed9.master.macOS-10-14.x86_64 $ open Emacs.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/william/scm/sandinmyjoints/build-emacs-for-macos/builds/Emacs.2021-07-25.a45aed9.master.macOS-10-14.x86_64/Emacs.app.
```

I deleted the build and sources, then rebuilt with `./build-emacs-for-macos --git-sha a45aed9479f610bcbc7a171b60d915fefc9b586a master` but got the same result.

I don't know if this is something that can be fixed on your end. Perhaps it's related to me running an older version of macOS and my only option is to upgrade. But thought I'd post here in case others run into it and/or have any ideas.

**Comment by jimeh** [comment]
I'm afraid I have not seen that issue before. Based on some quick searching, it looks like it might be a permissions issue with `Emacs.app/Contents/MacOS/Emacs`, double check if it's executable, and chmod `+x` if it isn't. There's some more details about Gatekeeper too here: https://stackoverflow.com/a/57020674/42146

If all else fails, I'd suggest trying a nightly build from my builds repo (https://github.com/jimeh/emacs-builds) to try to figure out if it's related to your machine running the app, or something with the build process itself on your machine.

**Comment by sandinmyjoints** [comment]
Thanks for the reply. I had tried most of what you linked above already w/o success. Hadn't tried a nightly build yet, but before I did that, one more thing I tried seemed to work. I granted Full Disk Access (via System Preferences -> Security and Privacy -> Privacy) to Emacs. I'm sure I had done this for Emacs in the past, but doing it again seems to have solved the problem. Perhaps the recent update I applied wiped previously granted permissions or something along those lines.

An odd note about these permissions -- I have multiple Emacs.app bundles with slightly different names from building different versions of Emacs over the past year or so. It seems like if I grant Full Disk Access to one of them, it is granted to all of them. This feature works...strangely, like so much about Apple's security work over the past few years.

**Comment by sandinmyjoints** [comment]
I ran into this again, after a reboot. What I wrote above about granting full disk access was not helping. Neither my Emacs built from this repo, nor another Emacs I installed from emacs-plus homebrew, would start -- both failed with this error. 

I eventually found that they would start fine with `-q`. So I went through my .emacs.d, and tracked the problem down to package-quickstart.el. Once I got rid of it, this error went away. I don't know what about it caused macOS to be so grumpy.

**Comment by jimeh** [comment]
Oh, that's interesting. I wasn't even aware of package-quickstart.el as I've been using straight.el for quite some time now. I'll try and find some time to test it myself to see if it's something I reproduce, and if it's related to something specific that the build script does outside of the normal Emacs build process.
