### ISSUE TITLE
source-directory is "/Users"

### ISSUE THREAD

**Issue by codesuki** [jimeh/build-emacs-for-macos#68]
Hi! Thanks for this nice and easy to use tool, I replaced my shell script with it :) 

I wanted to look into the code of `kill-buffer` and got an error that sources could not be found.
I saw this in `site-start.el`
```
;; Allow Emacs to find bundled C sources.
(setq source-directory (expand-file-name ".."))
```

So it seems when this gets executed the working directory is my user directory. ("/Users/name")

**Comment by jimeh** [comment]
Ha, indeed so it is. That's interesting, when I first implemented that, it was being set to `..` relative to the `site-start.el` file in `Emacs.app/Contents/Resources/lisp`.

**Comment by jimeh** [comment]
Turns out it took less than two minutes to find, test, and commit a fix :)

**Comment by jimeh** [comment]
You can fix it in already built `Emacs.app` bundles, avoiding a full re-build, by modifying `Emacs.app/Contents/Resources/lisp/site-start.el`, changing this:

```elisp
;; Allow Emacs to find bundled C sources.
(setq source-directory (expand-file-name ".."))
```

To this:

```elisp
;; Allow Emacs to find bundled C sources.
(setq source-directory
      (expand-file-name ".." (file-name-directory load-file-name)))
```

**Comment by codesuki** [comment]
That was quick! Thanks a lot :)
