### ISSUE TITLE
How to disable building with dbus?

### ISSUE THREAD

**Issue by Eason0210** [jimeh/build-emacs-for-macos#69]
Hi @jimeh,

Thanks for your great project.

I use `./build-emacs-for-macos` to build emacs 29, but will got these warning:

```bash
dbus[86536]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!loaded
```
Because I don't use dbus on macOS, is there an option to disable it?

**Comment by Eason0210** [comment]
Now， I can make work with running `brew services start dbus`, and then there are no warning anymore.

more details about dbus is here:
https://github.com/zbentley/dbus-osx-examples/blob/master/installation/README.md#using-homebrew-service-management

**Comment by jimeh** [comment]
Apologies for the late response. I'll add a flag to the build script to allow explicitly disabling dbus by passing `--without-dbus` to the configure script. This way people who don't care about dbus and don't want these warnings, can avoid it :)
