### ISSUE TITLE
libgccjit 11.3 replace .so file to .dylib let `libgccjit_lib_dir` become empty.

### ISSUE THREAD

**Issue by ccqpein** [jimeh/build-emacs-for-macos#71]
I update `gcc` and `libgccjit` this morning and the `libgccjit.so` file in `/usr/local/opt/libgccjit/lib/gcc/` changed to `libgccjit.0.dylib`. And it make `libgccjit_lib_dir` become empty [line 1128](https://github.com/jimeh/build-emacs-for-macos/blob/c2fb07fdb8bd95368e58aea3c1227c324c5fe024/build-emacs-for-macos#L1128)

Sounds like they keep this change in future versions [disscussion](https://github.com/orgs/Homebrew/discussions/3222#discussioncomment-2656482). 

Do we have configuration filter or options can make `build-emacs-for-macos` use `libgccjit.dylib` instead of `.so`? 

Thank you

**Comment by Eason0210** [comment]
I also got this issue after `brew upgrade`.
when build emacs, will got this error:
```
==> CMD: ./autogen.sh
Checking whether you have the necessary tools...
(Read INSTALL.REPO for more details on building Emacs)
Checking for autoconf (need at least version 2.65) ... ok
Your system has the required tools.
Running 'autoreconf -fi -I m4' ...
You can now run './configure'.
==> INFO: Detecting native-comp support: Supported
==> INFO: Compiling from source. This will take a while...
==> INFO: Compiling with native-comp enabled
ERROR: Detected GCC and libgccjit library paths do not belong to the same major
version of GCC. Detected paths:
  - /usr/local/opt/gcc/lib/gcc/11
  -
```
And emacs-plus have been fix it.
https://github.com/d12frosted/homebrew-emacs-plus/issues/455

**Comment by ccqpein** [comment]
@Eason0210 thanks for your reply. Depends on the discussion in the [link](https://github.com/d12frosted/homebrew-emacs-plus/issues/455), looks like the master version of emacs can accept `dylib` now.

I change line 1129 to `File.join(libgccjit_root_dir, 'lib/gcc/*/libgccjit.0.dylib*')` and it works. 

But do we need to keep the old `.so` options there? I dont know ruby, so I left my solution here and wish author or someone else can make a PR for it.

**Comment by jimeh** [comment]
Thanks for this report and information, I'll have a look and push a fix tonight :)
