### ISSUE TITLE
After latest update to libgccjit (11.3.0_1) emacs-28 does not compile

### ISSUE THREAD

**Issue by alicerum** [jimeh/build-emacs-for-macos#72]
New `libgccjit` brew package now contains `dylib` instead of `so`, and configure cannot find `gccjit` compatibility anymore, and `emacs-28` build fails.
Already compiled emacs obviously doesn't work anymore either.

`master` branch build succeeds though.

**Comment by alicerum** [comment]
```
dirname: missing operand
Try 'dirname --help' for more information.
checking for gcc_jit_context_acquire in -lgccjit... no
configure: error: ELisp native compiler was requested, but libgccjit was not found.
Please try installing libgccjit or a similar package.
If you are sure you want Emacs be compiled without ELisp native compiler,
pass the --without-native-compilation option to configure.
ERROR: Exit code: 1
```

**Comment by jimeh** [comment]
Yep, you are right. It's an issue with Emacs itself. The Makefile in `master` has been patched to support the newer `libgccjit` package, but that hasn't made it back to the `emacs-28` branch.

I haven't gotten around to looking into a solution properly yet, but my rough plan is to have my build script simply attempt to patch the Makefile.

**Comment by alicerum** [comment]
@jimeh awesome, thank you for the confirmation. For now I've installed the `master` branch build and it actually works fine. should I close the issue or let it be here until there is a solution for `emacs-28`?

**Comment by jimeh** [comment]
Emacs 28 should now be buildable again. Also as of 24th of July, the `emacs-28` branch was had the fix from `master` backported to it with this commit: https://github.com/emacs-mirror/emacs/commit/f7fd7bf477acfc65701065ec70c32dacb17e275a
