### ISSUE TITLE
Investigate support for new built-in tree-sitter support

### ISSUE THREAD

**Issue by jimeh** [jimeh/build-emacs-for-macos#78]

**Comment by mok0** [comment]
I found I had to
```
brew install tree-sitter
```
before Emacs would compile. (I also had to brew install ` libgccjit` and `texinfo`.)

**Comment by jimeh** [comment]
@mok0 yep, those are already listed in the `Brewfile`. If you run `brew bundle` it will install everything from that file.

This issue is actually resolved already as of a few months ago, turned out to be so easy I forgot about this issue... lol
