### ISSUE TITLE
`brew bundle` doesn't work…

### ISSUE THREAD

**Issue by askrix** [jimeh/build-emacs-for-macos#83]
Hello everyone 👋🏼,

After cloning the project, I followed the installation procedure described in `README.md`. As of it now, `brew bundle` doesn't work for me. Particularly, the following error message has been shown:
```sh
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Error: key not found: "osx-cross/arm/arm-gcc-bin@8"
Did you mean?  "osx-cross/arm/arm-gcc-bin@10"
```
Please see the attached screenshot with the complete stack trace
<img width="981" alt="Screenshot 2023-04-02 at 19 33 24" src="https://user-images.githubusercontent.com/37047795/229369235-386c6fd4-311f-482f-b965-34e5b4544d9d.png">

I tried my best to google for workarounds for the installation of `arm-gcc-bin@8-2019-q3-update`, since there is no available formula for it 
<img width="1413" alt="Screenshot 2023-04-02 at 19 38 11" src="https://user-images.githubusercontent.com/37047795/229369446-16bff0c6-6bb4-4490-894a-c89d6a11f309.png">

Furthermore, the current version seems to be $12.2$
<img width="1438" alt="Screenshot 2023-04-02 at 19 40 33" src="https://user-images.githubusercontent.com/37047795/229369600-18cb480f-1db7-4c6f-b805-404a96d378c7.png">

Thus, my question is if I have been missing something of requirements, or it is an actual issue to be reported?

Many thanks in advance!
Cheers, 🍻 

P.S.: I have MacBook Pro 2019's version with Ventura 13.2.1 (22D68) running.

**Comment by jimeh** [comment]
This sounds very much like a Homebrew issue. I'm not sure why it's trying to grab ARM binaries since you're on an Intel based Mac.

That said, it's been a while since I tried building Emacs locally. And I have instead just been relying on my [emacs-builds](https://github.com/jimeh/emacs-builds) project for the past year.

I'll leave this open for now until I have a chance to try a local build and see what's going on.

**Comment by askrix** [comment]
Thanks a lot @jimeh for the lightning quick response! Meanwhile, I will check out [`emacs-builds`](https://github.com/jimeh/emacs-builds). The reason, why I asked for help, is that it would be wonderful to try [`doom emacs`](https://github.com/doomemacs/doomemacs) with Emacs $v29$. The version is not being supported officially as of it yet, and I have trouble running [`docker.el`](https://github.com/Silex/docker.el).

Cheers, :beers:

**Comment by jimeh** [comment]
Not a problem. My emacs-builds project should work for you then. There's nightly builds both from master (30.x) and the emacs-29 branch.

Though master builds have been broken for a few days while I've been traveling, so should get around to sorting things out next week :)

**Comment by jimeh** [comment]
@askrix Apologies, I completely forgot to reply. I didn't have any issues running `brew bundle` locally. So I'm not sure I can really offer much help here, as it seems to be a Homebrew issue you were having.

**Comment by jimeh** [comment]
Having come back to look at this, I just realized it's complaining about packages in a tap called `osx-cross`.

That tap probably has conflicting formula names for `gcc` and/or `libgccjit` causing the issues, so you might need to remove that tap.

Alternative, the build script also supports managing build-time dependencies with Nix now, so you could give that a try as well.
