### ISSUE TITLE
App crashes using MacOS 14.0 Sonoma unless signed

### ISSUE THREAD

**Issue by ghost** [jimeh/build-emacs-for-macos#89]
Not sure if this happens to others but giving a heads up that my build on arm64 Sonoma crashed until I signed the app using the included go signer. Maybe Apple changed something in this latest version related to unsigned apps. Maybe want to add that in docs if others are experiencing this.

Anyway, I'm up and running now. Thanks for this awesome script! Love the speed of native compilation and that this is a pure edition.

**Comment by jimeh** [comment]
I'm fairly sure I fixed this some time ago, the build script always runs a self-sign step now, which is required on Apple Silicon machines for it to work at all.
