### ISSUE TITLE
Indicate necessary ruby version

### ISSUE THREAD

**Issue by px0** [jimeh/build-emacs-for-macos#9]
You may want to specify the necessary ruby version, as the macos pre-installed one is too old to work with the script. Thanks for setting this all up!

**Comment by jimeh** [comment]
Agreed. I plan to document required Ruby version, and ensure it'll run on older versions of Ruby as well. Just haven't had a chance to get to it yet :)

**Comment by jimeh** [comment]
Minimum required Ruby version is now 2.3.0, and readme clearly states so. Supporting 2.2.x or earlier would yield a bit more pain, so hopefully 2.3.0 and later is enough :)
