### ISSUE TITLE
Any plans to support `Stipples` 

### ISSUE THREAD

**Issue by CsBigDataHub** [jimeh/build-emacs-for-macos#97]
https://bitbucket.org/mituharu/emacs-mac/commits/25d1a744fc68eb8cd4e37443ac8ac3f7465f128e/raw

**Comment by jimeh** [comment]
My understanding is that there's no support or patch available for GNU Emacs which is what this script builds. The link is for `emacs-mac` which is a fork of mainline GNU Emacs as far as I know.

Adapting that commit to be compatible with GNU Emacs is very much outside my area of expertise. It might be worth asking on the emacs-devel mailing list about stipple support being officially added for macOS.

**Comment by CsBigDataHub** [comment]
Thanks for responding. I will try to reach out to them.
